@echo off
REM Generated by trunk tool 'bandit'
set PATH=C:\Users\Joey\AppData\Local\trunk\tools\bandit\1.7.5-06e6519fd70c8bb7d1c78c7d905f29ad/bin;C:\Users\Joey\AppData\Local\trunk\tools\bandit\1.7.5-06e6519fd70c8bb7d1c78c7d905f29ad/Scripts;C:\Users\Joey\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\Joey\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\Joey\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Joey\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set VIRTUAL_ENV=C:\Users\Joey\AppData\Local\trunk\tools\bandit\1.7.5-06e6519fd70c8bb7d1c78c7d905f29ad
set PYTHONUTF8=1
set HOME=%HOME%
if not defined HOME set HOME=

start /w /b bandit %*
