@echo off
REM Generated by trunk tool 'black'
set HOME=%HOME%
if not defined HOME set HOME=
set VIRTUAL_ENV=C:\Users\Joey\AppData\Local\trunk\tools\black\23.9.1-48fc27148136fd745c7fb65b02ab8647
set PYTHONUTF8=1
set PATH=C:\Users\Joey\AppData\Local\trunk\tools\black\23.9.1-48fc27148136fd745c7fb65b02ab8647/bin;C:\Users\Joey\AppData\Local\trunk\tools\black\23.9.1-48fc27148136fd745c7fb65b02ab8647/Scripts;C:\Users\Joey\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\Joey\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\Joey\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Joey\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b black %*
