@echo off
REM Generated by trunk tool 'isort'
set PATH=C:\Users\Joey\AppData\Local\trunk\tools\isort\5.12.0-7cbafcf3d8a727dbdea7bf5e45b0d688/bin;C:\Users\Joey\AppData\Local\trunk\tools\isort\5.12.0-7cbafcf3d8a727dbdea7bf5e45b0d688/Scripts;C:\Users\Joey\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\Joey\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\Joey\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Joey\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set VIRTUAL_ENV=C:\Users\Joey\AppData\Local\trunk\tools\isort\5.12.0-7cbafcf3d8a727dbdea7bf5e45b0d688
set PYTHONUTF8=1
set HOME=%HOME%
if not defined HOME set HOME=

start /w /b isort %*
