@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\Joey\AppData\Local\trunk\tools\osv-scanner\1.5.0-76bffb05173b9a3784356116baeccd3e;C:\Users\Joey\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Joey\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
