@echo off
REM Generated by trunk tool 'prettier'
set NODE_PATH=C:\Users\Joey\AppData\Local\trunk\tools\prettier\3.1.0-2115d831e02167aaad1518c9d39203db/node_modules
set HOME=%HOME%
if not defined HOME set HOME=
set PATH=C:\Users\Joey\AppData\Local\trunk\tools\prettier\3.1.0-2115d831e02167aaad1518c9d39203db/node_modules/.bin;C:\Users\Joey\AppData\Local\trunk\tools\node\18.12.1-ee91e409de31a08a96aaff7f742f83b4/bin;C:\Users\Joey\AppData\Local\trunk\tools\node\18.12.1-ee91e409de31a08a96aaff7f742f83b4;C:\Users\Joey\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Joey\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b prettier %*
