@echo off
REM Generated by trunk tool 'ruff'
set PATH=C:\Users\Joey\AppData\Local\trunk\tools\ruff\0.1.7-dedda99e6825b3b91bd6c573453c3e2a/bin;C:\Users\Joey\AppData\Local\trunk\tools\ruff\0.1.7-dedda99e6825b3b91bd6c573453c3e2a/Scripts;C:\Users\Joey\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\Joey\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\Joey\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Joey\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set VIRTUAL_ENV=C:\Users\Joey\AppData\Local\trunk\tools\ruff\0.1.7-dedda99e6825b3b91bd6c573453c3e2a
set PYTHONUTF8=1
set HOME=%HOME%
if not defined HOME set HOME=

start /w /b ruff %*
