@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\Joey\AppData\Local\trunk\tools\trufflehog\3.63.2-fb64ac62d7f933ca78c8450bbc7fc8cf;C:\Users\Joey\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Joey\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
